### PR TITLE
Update FOLLOW set for `ty` tokens

### PR DESCRIPTION
**Pull request by alexcrichton**
Accounts for rust-lang/rust#27000

cc @cmr

### CODE REVIEW

**Comment by cmr** [comment]
r+

**Comment by nikomatsakis** [comment]
cc @pnkfelix

**Comment by nikomatsakis** [comment]
Hard to argue against this!

**Comment by nikomatsakis** [comment]
To be clear, did code for this already land?

**Comment by alexcrichton** [comment]
@nikomatsakis yeah it landed in https://github.com/rust-lang/rust/pull/27000 (although we can revert if we don't want to accept this RFC)

**Comment by dgrunwald** [comment]
Any reason we don't allow `{` after `ty`?
In particular, I'd like to write a macro that mimics function definition syntax:
`($paramname:id) -> $rettype:ty $body:block`

**Comment by nikomatsakis** [comment]
@dgrunwald yes, seems like there isn't a good one. also `where` keyword.

**Comment by huonw** [comment]
cc #733

**Comment by nikomatsakis** [comment]
Hear ye, hear ye. This RFC is entering **final comment period**.

/me thought it already was

**Pull request merged**
