### PR TITLE
Add singlethreaded (compiler-only) fences.

### PR DESCRIPTION
**Pull request by tari**
[Rendered.](https://github.com/tari/rfcs/blob/compiler-fences/text/0000-compiler-fence-intrinsics.md)

### CODE REVIEW

**Comment by pythonesque** [comment]
This seems pretty useful, +1.

**Comment by reem** [comment]
Agreed.

**Comment by oli-obk** [comment]
alternatives: using `black_box` instead. parameters to `black_box` are not moved after results of `black_box`. allows fine-grain fences.

**Comment by brson** [comment]
Why does the llvm reference say 'this is useful for interacting with signal handlers'? Reading the docs for atomic_signal_fence does not enlighten.

**Comment by tari** [comment]
My understanding is that signals preempt the thread or process receiving them, meaning they will execute on the same physical thread. Because there's no hardware context switch, memory reordering is not a concern since operations always appear to happen in program order within a single thread's context.

If code interacts with signal handlers via memory, compiler reordering of memory operations may change the order of operations as seen by the signal handler (which the compiler is not aware of), potentially violating program-maintained invariants.

---

Neglected to mention it elsewhere; this RFC comes from [Rust PR #22358](https://github.com/rust-lang/rust/pull/22358), which includes an implementation.

**Comment by brson** [comment]
Accepted. Tracking bug https://github.com/rust-lang/rust/issues/24118. Sorry for the long delays.

**Pull request merged**
