### PR TITLE
Move some net2 functionality into libstd

### PR DESCRIPTION
**Pull request by sfackler**
[Rendered](https://github.com/sfackler/rfcs/blob/net2/text/0000-net2-mutators.md)

### CODE REVIEW

**Comment by alexcrichton** [comment]
:bell: This RFC is now entering its week-long **final comment period** :bell: 

Please don't everyone comment all at once!

More seriously, though, the libs team is interested specifically in diving into the landing strategy for this in libstd, either:

* This new functionality lands insta-stable
* The new functionality lands as an unstable extension trait

---

My own personal opinion is that we should land these as insta-stable. The APIs have been vetted in net2-rs for quite some time now, and I don't think we'd really gain all that much more use through another round of FCP for the APIs.

Curious what others think though!

**Comment by briansmith** [comment]
I don't think these should be added via traits. Over time, the standard library would become a ridiculous mess of such traits as new functionality is added, if it were to follow that pattern.

**Comment by sfackler** [comment]
The traits would only exist until the methods were stabilized.

**Comment by alexcrichton** [comment]
The libs team discussed this during triage yesterday and the conclusion was to merge this RFC adding these methods as insta-stable. Thanks for the RFC @sfackler!

**Comment by sfackler** [comment]
We're going to hold off until just after the next release to allow for the longest possible time before these hit a stable release and are locked in forever.

**Comment by tshepang** [comment]
How about simply not making them insta-stable?

**Pull request merged**
