### PR TITLE
Propose RFC for IpAddr common methods

### PR DESCRIPTION
**Pull request by mathphreak**
[rendered](https://github.com/mathphreak/rfcs/blob/master/text/0000-ipaddr-common-methods.md)

### CODE REVIEW

**Comment by eefriedman** [comment]
Please include the exact signature of the proposed methods in the proposal... something like this:

```
impl IpAddr {
    fn is_loopback(&self) -> bool { ... }
    fn is_multicast(&self) -> bool { ... }
}
```

**Comment by mathphreak** [comment]
@eefriedman Just added that.

**Comment by Ryman** [comment]
Similar suggestion (without required details) https://github.com/rust-lang/rfcs/issues/1554 cc @canndrew

**Comment by sfackler** [comment]
It looks like there are some other shared methods between the two types (`is_documentation`, etc). Seems like we should probably add them all at once?

**Comment by mathphreak** [comment]
@sfackler I only mentioned the stable methods. If it would be better to list all of them, I can make that change.

**Comment by sfackler** [comment]
Yeah I figure we should add all of them - these new methods would land unstable anyway.

**Comment by mathphreak** [comment]
@sfackler Done.

Also, I noticed that Ipv4Addr has an `is_link_local()` method, while Ipv6Addr has an `is_unicast_link_local()` method. It seems like those are nearly the same; should I add an `is_link_local()` as well?

**Comment by sfackler** [comment]
I don't think I know enough about IPv6 to be able to answer that :)

**Comment by mathphreak** [comment]
Neither do I. Unless an IPv6 expert shows up and says that those are the same, I think it's best to leave `is_link_local()` out.

**Comment by alexcrichton** [comment]
I'm actually surprised to see this RFC because I thought these methods already exists! I could have sworn we either had PR or an issue about this...

@mathphreak this is actually the kind of addition where the libs team generally doesn't require an RFC. If you'd like to close this out and send a PR directly to rust-lang/rust proposing this change, I suspect we'd merge pretty quickly!

**Comment by mathphreak** [comment]
@alexcrichton I wasn't quite sure if that was the case. I'll get right on that. I'll leave this open until I submit that PR.

**Comment by mathphreak** [comment]
That took longer than expected, but https://github.com/rust-lang/rust/pull/34694 is now live.

**Pull request closed without merging**
