### PR TITLE
Rename 2071-impl-trait-type-alias.md to 2071-impl-trait-existential-types.md

### PR DESCRIPTION
**Pull request by jethrogb**
Renaming to match feature name

### CODE REVIEW

**Comment by Centril** [comment]
I prefer not to do this as there may be links in the wild to the document which would 404. If you leave a file in place with a link to the new file address then I would be more positively inclined.

**Comment by jethrogb** [comment]
Did that, but it looks like GitHub doesn't support symlinks very well.

**Comment by Centril** [comment]
Try a file with an actual hyperlink instead :)
It takes the reader one more click but at least it will work.

**Comment by Centril** [comment]
Works for me :) Thanks!

**Comment by Centril** [comment]
Works for me; Thanks!

**Pull request merged**
