### PR TITLE
Ban private items in public APIs

### PR DESCRIPTION
**Pull request by glaebhoerl**
[Pretty](https://github.com/glaebhoerl/rfcs/blob/no-privates-in-public/active/0000-no-privates-in-public.md)

### CODE REVIEW

**Comment by pnkfelix** [comment]
Hey, privacy experts: Is this actually a problem: https://github.com/rust-lang/rust/issues/17697 ?

**Comment by glaebhoerl** [comment]
My first guess is that this is just useless - you can't expose a private type, so there's no way its field being public could have any relevance - and so it's worth warning about, but not imperative to forbid. But it's possible that I'm missing something.

**Comment by dhardy** [comment]
I have an issue with this RFC: it does not explain what is meant by the word *public* within the RFC text. What does it mean?

1.  That an item is usable within the module it is declared, but not necessarily outside that module
2.  That an item can be used in some way outside the crate, but without the requirement that it be nameable
3.  That an item be usable and nameable (the "public path" thing) from outside the crate

The meaning of this sentence, which is key to interpreting the RFC, is thus unclear:

> Items that are explicitly declared as `pub` are always public.

From the comments at the bottom, I'm guessing "public" means 2. Unfortunately, this still leaves the issue of how to document the "unnameable" type, but I guess that can be dealt with (though it means using the name of a private module, most likely).

**Comment by petrochenkov** [comment]
>Unfortunately, this still leaves the issue of how to document the "unnameable" type, but I guess that can be dealt with

Let's say a function return a value of unnameable type. The the docs on this function can describe what a user of this function can do with that value. For example, C++ docs do [this](http://en.cppreference.com/w/cpp/utility/functional/bind) when return type of something is *unspecified*.
Ideally such functions should return something like https://github.com/rust-lang/rfcs/pull/1305 and not unnameable types.

FWIW, I tweaked the privacy pass to apply more strict rules (variant 3 from your list) and run it on rustc and standard library. Most of broken code contained actual deficiencies - types that should have been nameable, but weren't reexported by accident.

**Comment by petrochenkov** [comment]
@dhardy 
Also, this PR is not the actual version of the RFC, there's a later revision, which changes the rules completely.

**Comment by dhardy** [comment]
@petrochenkov I realise this isn't the latest PR for the RFC. The RFC should probably link to both PRs.

Also, I am not surprised that variant 3 works for most code. If you read *this* PR, it reads two uses for exporting "private" (unnameable) items, and in both cases better solutions (type aliases/deriving new-types, and private trait members). IMO that would be the better solution than the current RFC, but it's not really important.

What I don't like about current RFC (aside from the contradiction in allowing `pub` on members of private structs) is that if you read it with variant 3 of my list in mind, it still all makes sense, with the sentence I quoted above then meaning *it is an error if an item marked `pub` is not public (i.e. nameable)`. Confusing.

**Pull request merged**
