### PR TITLE
RFC: Extend pattern syntax

### PR DESCRIPTION
**Pull request by ftxqxd**
[Rendered view](https://github.com/P1start/rfcs/blob/pattern-syntax/active/0000-extend-pattern-syntax.md)

### CODE REVIEW

**Comment by mdinger** [comment]
Another use case for extending the pattern matching which is *slightly* similar to https://github.com/rust-lang/rfcs/issues/673:
```rust
use E::*;

enum E {
    A(i32, i32),
    B(i32, i32),
}

fn main() {
    let a = A(6, 9);
    let b = B(3, 8);

    // Works but really tedious. Don't try triples or quads...
    match (a, b) {
        (A(x, y), B(z, t)) |
        (B(x, y), A(z, t)) |
        (A(x, y), A(z, t)) |
        (B(x, y), B(z, t)) => println!("x: {}, y: {}, z: {}, t: {}", x, y, z, t),
    }

    // One possible solution. Both `_` are ignored but can be either `A` or `B`.
    // Applied to the more complex case.
    match (a, b) {
        (_(x, y), _(z, t)) @_ A | B => {},
    }

    // It uses `@T` to specify a specific variable.
    match a {
        A(x, y) @x 3 => {}, // bind x to 3
    }
}
```

I'm not thrilled with `@T` but it does seem clear to me and I don't see any obviously better syntax ideas for this.

**Comment by Ticki** [comment]
This should be reopened.

**Comment by taralx** [comment]
:+1:

**Comment by whitequark** [comment]
@alexcrichton Please reopen this.

**Comment by White-Oak** [comment]
@whitequark there was a subset of this: #1500 which gor postponed as well, so I guess, *not yet*.

**Comment by whitequark** [comment]
@White-Oak MIR was merged though.

**Comment by sanmai-NL** [comment]
@nikomatsakis, @alexcrichton: You can quickly conclude from the above comments, that this PR ought to be reopened now. Could you please take this action (right away) or let everyone involved know why, in case you disagree somehow? This topic has led to multiple issue filings (e.g., #929, #2150, #551). Could someone with responsibility step in and reorganize the discussion (e.g. close duplicate issues and refer to this PR or so), to start with?

**Comment by aidanhs** [comment]
@aturon made a comment in the RFC @White-Oak linked:

> In a future incarnation of this RFC, we'd like to see more detailed motivation with real-world use-cases where the feature makes a significant impact.

Which seems to indicate a new RFC that includes this additional detail would be more appropriate than reopening this one (otherwise the lang team would presumably just reach a similar conclusion). I also don't see the need to 'reorganise' the discussion when it's not clear what form extending pattern matching would take (incrementally, with `if let &&` and others as separate RFCs each with their own motivational use-cases, or as one overhaul).

(personally I would love this RFC, but I guess a new one with the bits I mentioned above would be more appropriate)

**Comment by sanmai-NL** [comment]
@aidanhs: If @aturon’s comment in that other thread is conclusive, then I’d expect the persons responsible (him? the people I pinged?) to address the outstanding issue threads some of which I mentioned (i.e., close them) and to respond to the calls for reopening this PR here with a clear statement. That is what I mean with reorganizing the discussion.

Enhancement of the pattern syntax in `if let` vs. `match` seems to get ‘a lot’ of attention from Rust people here on GitHub, so it isn’t so obvious such an enhancement is little desired. I am not too familiar with RFC procedures but if just the motivation section of an RFC could still be improved, I don’t see why the whole RFC should be started over. Esp. if the motivation is apparent but just not laid out well enough in the RFC.

**Comment by Centril** [comment]
Parts of this RFC has already been lifted in #2175 . I suspect more of it will be lifted later in other RFCs as well.

**Pull request closed without merging**
