### PR TITLE
Feature gate box patterns

### PR DESCRIPTION
**Pull request by jakub-**
[Rendered view](https://github.com/jakub-/rfcs/blob/c539b10a99c59bb96ba4657ff9263e2074aaa637/text/0000-feature-gate-box-patterns.md)

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I'm taking over this RFC. Given the [previous discussion](https://github.com/rust-lang/rfcs/pull/469#issuecomment-66361609) I think the time is ripe to accept this RFC.

**Comment by sanmai-NL** [comment]
@steveklabnik: The link to the RFC in the OP is broken. Am I correct to assume you would be the one to fix it? Not sure how you could, since the poster’s account has been deleted.

**Comment by pnkfelix** [comment]
One can fix it by pointing to the blob that remains in the local repo instead of the poster's. Which I will do now.

**Comment by pnkfelix** [comment]
Also, for RFCs that have been accepted, the more traditional fix is to point the link to the text file in the rfcs repo itself, so that people who follow the link will see any future amendments/updates to that text.

**Pull request merged**
