### PR TITLE
RFC for creation of `IntoRaw{Fd, Socket, Handle}` trait to complement `AsRaw*`

### PR DESCRIPTION
**Pull request by ipetkov**
[Rendered](https://github.com/ipetkov/rfcs/blob/into-raw-trait/text/0000-into-raw-fd-socket-handle-traits.md)

### CODE REVIEW

**Comment by ipetkov** [comment]
cc @alexcrichton @aturon

**Comment by sfackler** [comment]
I like the idea of this functionality, but I'd go with `Into<RawFd>` etc instead of defining new traits. The common convention is to both implement `Into<Foo>` and add an `into_foo()` method to a type, since `Into` is useful in a generic context but can be a bit of a pain to use if you have a concrete `TcpStream` or whatever that has multiple `Into` impls.

**Comment by alexcrichton** [comment]
Unfortunately using `Into<RawFd>` means that when you convert an object to a file descriptor there's no platform-specific opt-in, you instead just call `let a: i32 = file.into()` and it becomes a portability hazard. In having separate traits you acknowledge the platform-specific-ness via `use std::os::unix::...`.

**Comment by sfackler** [comment]
Ah, yeah, that makes sense. I'm on board with `IntoRaw{Fd,Handle,Socket}` then.

**Comment by l0kod** [comment]
:+1:

**Comment by alexcrichton** [comment]
This RFC is now entering its week-long final comment period.

**Comment by alexcrichton** [comment]
The consensus of the libs team this week is to merge this RFC, so I'm going to do so. Thanks again for the RFC @ipetkov!

[Tracking issue](https://github.com/rust-lang/rust/issues/27062)

**Pull request merged**
