### PR TITLE
Fix typo in fn variance

### PR DESCRIPTION
**Pull request by aidanhs**
Per https://github.com/rust-lang/rfcs/pull/738#discussion_r23849477

I'm a little unsure though since this hasn't been fixed for so long?

### CODE REVIEW

**Comment by eddyb** [comment]
cc @rust-lang/lang

**Comment by aidanhs** [comment]
> Finally, there can be cases where it is ok to make a lifetime longer, but not shorter. This comes up when the lifetime is used in a function return type (and only a fn return type).

By the same line of thought, I think this is wrong as well and should refer to function arguments?

I.e. it is safe to treat a `fn(&'a T)` as a `fn(&'static T)`

**Comment by nikomatsakis** [comment]
Looks like a correct typo.

**Comment by nikomatsakis** [comment]
Er, a correct fix =)

**Pull request merged**
