### PR TITLE
Mention RFC 1201 was superseded by RFC 2972

### PR DESCRIPTION
**Pull request by JohnTitor**
See the [summary comment](https://github.com/rust-lang/rust/issues/32408#issuecomment-1016931986) for details.

### CODE REVIEW

**Comment by tbu-** [comment]
Duplicate #3223.

**Comment by JohnTitor** [comment]
@joshtriplett To show the removal, seems you prefered this PR's style in https://github.com/rust-lang/rfcs/pull/3154#issuecomment-886015212, but  #3223 has another style, which ones do you prefer?

**Comment by Nilstrieb** [comment]
Going to merge this, as it seems useful enough. We can always change the style later.

**Comment by JohnTitor** [comment]
Thank you for taking care of this!

**Pull request merged**
