### PR TITLE
Unchecked downcast methods for Any

### PR DESCRIPTION
**Pull request by chris-morgan**

### CODE REVIEW

**Comment by 0xc0170** [comment]
[Rendered](https://github.com/chris-morgan/rfcs/blob/unchecked-downcast-methods-for-any/text/0000-unchecked-downcast-methods-for-any.md)

**Comment by reem** [comment]
I never checked, but I'm curious if the checks in regular `Any` methods are optimized away by LLVM in cases like AnyMap and TypeMap, where the types are pretty simple and should be exposed during monomorphization.

That said, I still think this is a good idea, I've though unsafe-any could be moved into std for a while.

**Comment by pythonesque** [comment]
Is this different from `transmute_copy` (to turn the fat pointer into a thin one of the appropriate type)?  If not it seems kind of weird to have a specific method for it in the standard library.  That is, I understand creating wrappers around transmute in instances where the transmute is safe, but in general this is just as unsafe as an ordinary transmute.

**Comment by chris-morgan** [comment]
@reem: an `impl Box<Any>` in liballoc works just fine, since `Box` is defined in liballoc, so there is no change to anyone. libcore can use all its `&Any` and `&mut Any` methods, anything using liballoc can use the `Box<Any>` methods.

**Comment by chris-morgan** [comment]
@pythonesque an unchecked downcast is `transmute(transmute::<_, TraitObject>(self).data)`. Do you want people writing *that* everywhere? That is a lot more prone to problems than this.

**Comment by alexcrichton** [comment]
@chris-morgan could you add some wording here that these APIs will all land as initially `#[unstable]` as well? We'd like new APIs to enter the standard library as `#[unstable]` in general and bake for a bit before being promoted to `#[stable]`.

You may also want to go ahead an decided on a feature name for these methods as the [related implementation](https://github.com/rust-lang/rust/pull/21248) is likely to land soon.

**Comment by aturon** [comment]
ping @alexcrichton 

I'm personally ambivalent about this convenience, but would be OK landing it `unstable` and then stabilizing by demand.

**Comment by alexcrichton** [comment]
Thanks again for the RFC @chris-morgan! It's looking like there's not necessarily a great need to land and stabilize these functions right now, however, so I'm going to close this for now. These methods are minor enough and have pretty clear semantics/naming that it's also likely that they can land pretty easily at any time as well.

**Pull request closed without merging**
