### PR TITLE
Rename or replace `str::words` to side-step the ambiguity of “a word”.

### PR DESCRIPTION
**Pull request by SimonSapin**
[View](https://github.com/SimonSapin/rfcs/blob/str-words/text/0000-str-words.md).

### CODE REVIEW

**Comment by steveklabnik** [comment]
:+1: from me

**Comment by SimonSapin** [comment]
Some relevant discussion starting here: https://github.com/rust-lang/rust/issues/15628#issuecomment-91707957

**Comment by nagisa** [comment]
I like the propsed approach. This provides a low-cost convenience wrapper to something many people will be getting wrong otherwise.

How wrong you ask? Splitting over the ASCII space only. Python does not provide any proper convenience wrapper in its standard library and in all code I’ve seen literally all word splitting is done over the ASCII space.

**Comment by SimonSapin** [comment]
“Wrong” depends on what you’re doing. Sometimes, you might be e.g. parsing a space-separated file formet and splitting on non-breaking spaces or other non-ASCII whitespace is not what you want. But `s.split(&[' ', '\t'][..])` or similar is available for that situation, and hopefully users will know the difference.

That said, I’m becoming less and less convinced that this should be included at all. I’d like to see use cases. (https://github.com/rust-lang/rust/issues/15628#issuecomment-91726492)

**Comment by SimonSapin** [comment]
And if you’re in a situation where considering only ASCII is wrong, isn’t considering only whitespace also wrong and shouldn’t you be looking for Unicode word boundaries? https://github.com/rust-lang/rust/issues/15628

**Comment by nagisa** [comment]
> you might be e.g. parsing a space-separated file formet and splitting on non-breaking spaces or other non-ASCII whitespace is not what you want

you shouldn’t use `words`/`split_whitespace` in this case anyway, because it is not `split_whitespace`’s purpose to split columns in ASCII space-delimited files.

> And if you’re in a situation where considering only ASCII is wrong, isn’t considering only whitespace also wrong and shouldn’t you be looking for Unicode word boundaries? 

Indeed. Since I’ve previously been doing web development almost exclusively, I found that people think words in prose will always have an ASCII space between them. Considering they will be separated by some unicode whitespace instead is just as wrong.

On the other hand, nothing in `split_whitespace` suggest it will produce a list of words. So, either just remove `words` completely, or deprecate it in favour of `split_whitespace`.

**Comment by iopq** [comment]
I think the standard library should only implement things that have an obvious "best" implementation. If there are too many complexities and questions about what IS best, it should be sorted out in the crates.io ecosystem.

**Comment by kballard** [comment]
:+1: on renaming to `split_whitespace`.

Just 2 days ago I wrote some code that needed to split a line on whitespace. Having `str::split_whitespace` would have been very useful to me. I actually forgot about `str::words` so I ended up writing `s.split(" ")`, which bugged me for the reasons you already listed (only split on space, and didn't collapse sequences of whitespace), although in my particular use-case it was acceptable.

FWIW I think I forgot about `str::words` because it's not grouped with either the `split_*` methods or with `lines()` (though it is grouped with `graphemes`). So in addition to renaming it, I think it should be moved to be adjacent to the other splitting methods for ease of discovery.

**Comment by kballard** [comment]
More generally, I think people expect that splitting on whitespace should be an easy thing to do. And I agree with them, it really should. It's not always the correct thing to do, but it's a common enough thing to want.

**Comment by kwantam** [comment]
I agree that splitting on whitespace is a common enough thing that providing a convenience function for it is a good idea, and that calling said function `words()` is a bit too imprecise.

Moving this function from libunicode into libcollections and renaming it `split_whitespace()` is the right approach here, I think. :+1:

**Comment by kballard** [comment]
Why move it out of libunicode?

**Comment by kwantam** [comment]
No particularly strong reason, but it seems to me that since it doesn't directly rely on any Unicode tables (though it does indirectly, though the `char::is_whitespace()` function; but this is itself exported), it can just live in libcollections instead.

**Comment by kballard** [comment]
The problem with moving it into libcollections is that means crates that only use libunicode/libcore (but not liballoc) lose access to this function.

Note that most of libcollections's `str` methods are actually just wrappers that call into libcore or libunicode. The only `str` methods implemented in libcollections directly are ones that require allocation (e.g. the methods that return `String`).

**Comment by kwantam** [comment]
Good point. :+1:

**Comment by tafia** [comment]
I personally think using `split` / `regex` is enough. It is almost a one-line expression that could easily be found with a simple google search in the future.

**Comment by kballard** [comment]
A regex is waaaay overkill for this problem, and `split()` doesn't collapse sequences of adjacent whitespace, so if we say "you have to use `split()`" then everyone has to remember "and add `.filter(|x| !x.is_empty())`"

**Comment by tafia** [comment]
You won't say to use split "only". You'll let them google it and then find
the one line split + is_empty (or whatever). For instance I couldn't easily
find an equivalent in c#, I google and quickly found simple answers).

I think std should
- remain as simple as possible
- focus on basic functionalities with not so basic implementations

But I am clearly not the best adviser, I just wanted to give my opinion.

**Comment by tshepang** [comment]
@kballard `s.split_whitespace()` is easier on the eyes than `s.split(char::is_whitespace).filter(|s| !s.is_empty())`. It's also a very common function.

**Comment by nikomatsakis** [comment]
:+1: Ship it!

**Comment by kwantam** [comment]
Slight sticking point: while `words()` is marked unstable, the `Words` iterator is marked stable. So probably a deprecation / transition plan is required here.

**Comment by huonw** [comment]
I wonder if this couldn't be tackled with a pattern API too, e.g. `s.split(std::str::Whitespaces)`, which would collapse runs of whitespace into one.

**Comment by alexcrichton** [comment]
Thanks again for the RFC @SimonSapin! The feedback on this has been quite positive, so I'm going to merge this. The fact that `Words` is `#[stable]` (as @kwantam pointed out) I believe was just a mistake and we should be fine to revert the stability. I also think that @huonw's idea is a plausible option, but it is probably more ergonomic to have an inherent method anyway (less imports). Regardless we'll have a bit more time after this lands as `#[unstable]` to tweak it for a bit as well.

**Comment by kballard** [comment]
Just to note, while I like @huonw's general idea of providing some pre-baked patterns for common things, I don't think that is actually a suitable replacement for `str::words()` because it won't be able to drop the empty first/last elements when the string has leading/trailing space (e.g. `" a b ".split(std::str::Whitespaces)` would yield `["", "a", "b", ""]`).

**Comment by kwantam** [comment]
It should be possible to provide a pattern for `match()` that does the right thing, though.

**Comment by kballard** [comment]
@kwantam Ah hmm, you're right. I actually didn't realize we had a `matches()` method now, though it seems like an obvious thing to have in hindsight.

**Pull request merged**
