### PR TITLE
Unapprove placement RFCs

### PR DESCRIPTION
**Pull request by aidanhs**
r? @nikomatsakis 

See https://github.com/rust-lang/rust/issues/27779#issuecomment-378416911 for reference.

### CODE REVIEW

**Comment by JustAPerson** [comment]
At first I was confused to see this, but after reading the linked threads I'm glad that you and others remain motivated in seeking perfection in this area! Thank you! We must be competitive with C++ :)

**Comment by aidanhs** [comment]
Is that common language for taking something accepted out of circulation? I tend to associate it with abandoning a proposal that hasn't been approved yet. I'd be happy using the language that another community/body/organisation users, but I couldn't think of any examples to draw from.

**Comment by clarcharr** [comment]
Could go with "retroactively closed/postponed." I'd say that these have been retroactively postponed to indicate that while the RFCs were originally accepted, in hindsight it makes more sense to act as if they were postponed, because they need better design to satisfy the guarantees.

**Comment by mark-i-m** [comment]
Repealed?

**Comment by clarcharr** [comment]
Question: do we need an FCP to revert an FCP?

**Comment by Ixrec** [comment]
Personally I think "retract" is the best term, though it's by a very small margin. Nitpicky arguments:

"Repeal" sounds too legalistic to me. It makes me imagine RFCs as proposals to modify the standardese text of the ISO Rust specification, such that repealing one in the future would imply making the opposite modification to the specification text. I think "Retract" manages to strike the ideal balance of sounding professionally formal without quite crossing into legalistically, only-comprehensible-for-wizards formal.

"Retroactively closed/postponed" sounds like the RFC should have been closed/postponed a long time ago, but for whatever reason it fell through the cracks and we simply forgot to do so. Since we accepted and implemented this RFC, then removed the implementation, that doesn't quite sound right to me.

"Unaccepted" would be my #2 choice. I like it slightly less than "retract" only because it sounds similar to "unacceptable", which is a somewhat judgmental word. But that's the only tiebreaker nitpick I can come up with.

**Comment by nikomatsakis** [comment]
We discussed in the @rust-lang/lang meeting and decided to resist the alluring bikeshed and just merge as is. (Note that FCP on this decision has already occurred.)

**Pull request merged**
