### PR TITLE
RFC: Add a new macro for "unreachable" whose meaning differs in debug and release builds

### PR DESCRIPTION
**Pull request by vojtechkral**
[Rendered View](https://github.com/vojtechkral/rfcs/blob/unreachable/text/0000-new-unreachable-macro.md)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Fwiw, something like this existed in Firefox but was removed: <https://bugzilla.mozilla.org/show_bug.cgi?id=990764>.

**Comment by reem** [comment]
I have this implemented as a library in use in lazy and once-mutex here: https://github.com/reem/rust-debug-unreachable.

**Comment by vojtechkral** [comment]
@reem FYI, in your implementation the macro isn't unsafe in debug builds...

**Comment by sfackler** [comment]
@vojtechkral `if false { <do unsafe thing }` is still an unsafe expression.

**Comment by vojtechkral** [comment]
@sfackler Ah, my bad, thanks for clarification...

**Comment by Ericson2314** [comment]
I'd like having unreachable, unwrap, potentially other things do this, but only with a new cfg-like thing called "unsafe release", in addition to existing "debug" and "release".

**Comment by alexcrichton** [comment]
Thanks for the RFC! This is something very easy to add at a future date if necessary and can today live quite well in a crates.io library, so I'm going to close this for now as postponed.

**Comment by kmcallister** [comment]
Did anyone end up making an external library for this?

**Comment by vojtechkral** [comment]
@kmcallister reem did, https://crates.io/crates/debug_unreachable

**Comment by Ticki** [comment]
Could this be reopened? This would allow lots of new optimizations.

**Comment by Ericson2314** [comment]
Hmm, while I am sympathetic to having this in the standard library, what possible optimizations aren't also available while its in a separate crate?

**Comment by Ticki** [comment]
@Ericson2314 None. You'd get the same outcome in a seperate crate, but it would be neat if the standard library had this built in.

**Comment by Ericson2314** [comment]
Ah ok.

**Pull request closed without merging**
