### PR TITLE
RFC for attributes on statements and blocks.

### PR DESCRIPTION
**Pull request by huonw**
Allow attributes on more places inside functions, such as statements and blocks.

### CODE REVIEW

**Comment by slimsag** [comment]
shouldn't this be removed from the [active RFC list](https://github.com/rust-lang/rfcs#active-rfc-list) if it's been accepted/merged?

**Comment by sfackler** [comment]
The active list contains RFCs that have been accepted but not implemented.

**Comment by Kimundi** [comment]
I'm currently in the process of implementing this, and in accordance with the current RFC text attributes will be initially prohibited on `if` expressions.

However, thinking about it I wonder if the following scheme could be used:

```rust
#[covers_remaining_three] if expr #[covers_block] {
    // ...
} else #[covers_remaining_two] if expr #[covers_block] {
    // ...
} else #[covers_block] {
    // ...
}
```

The idea being that an attribute before an `if` token applies to the whole, chained `if` expression, while a attribute before the block only applies to that block expression.

Of course, the "disadvantage" here is that for consistency you'd want to support those block-only attributes on anything taking a block, like the loop expressions. And then there would be more than one location per block-taking expression where a attribute might apply, which while not ambiguous could become potentially confusing.

**Comment by huonw** [comment]
@Kimundi, that is in fact one of the alternatives. I think nailing down this aspect of the behaviour is probably worth an amendment RFC.

**Pull request merged**
