### PR TITLE
Add a `trustme` keyword to define unsafe code blocks

### PR DESCRIPTION
**Pull request by yggdrasil48**

### CODE REVIEW

**Comment by qq523915712** [comment]
disagree with this poor idea.

**Comment by crlf0710** [comment]
[Rendered](https://github.com/rust-lang/rfcs/blob/1d0f99b760fcdf255c99a00fd7194e4b80d69f4a/text/0000-trustme-keyword.md)

**Comment by ZhangHanDong** [comment]
trust me this time

**Comment by qq523915712** [comment]
unsafe is not enough,we should use unsafe_code_here_is_very_dangerous{
println!("hello,world");
}

**Comment by fstirlitz** [comment]
Actually, there’s been some serious talk of disambiguating the ‘definition-site’ unsafe from ‘user-site’  unsafe: #2585 contains some discussions (look for `trusted`).

**Comment by yggdrasil48** [comment]
This PR will be closed at 23:59 1nd April 2020 UTC-12.

**Comment by superobertking** [comment]
And the rustc would have a message like:
```
error[EAPR1]: trust problem
 --> trustme.rs:2:5
  |
2 |     rustc_trustme_from_this_point_forward_for_unsafe_for_safe_for_imprudent_for_exquisite_in_segfault_and_in_panic_until_bsod {
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ I do.
  |
  = note: rustc does not speak truthfully today

error: aborting due to previous error
```

**Comment by x1957** [comment]
nice idea!

**Comment by PsiACE** [comment]
Why not `I_know_what_im_doing_shut_up_ur_fk_mouth_and_I_promise_its_abosulte_safe`?

**Comment by recapitalverb** [comment]
Computers have no emotion and cannot "trust" like us humans do -- I'm against using `trustme` with the reason being it would be just as misleading as `unsafe` itself.

As a better alternative, I propose the following:

```rust
safe { libc::srand(0); }
```

**Comment by spacekookie** [comment]
Being entirely serious, a `trust` kind of keyword would remove a lot of confusion people have about `unsafe`. Because ultimately you're telling the compiler to not check your code, not that it's unsafe. Ideally it would be safe, just that you have to be sure it is.

**Comment by phper-chen** [comment]
shut_up_and_take_my_code {
   .......code
}

**Comment by yggdrasil48** [comment]
Thank you all for tolerating this April 1st joke.

**Pull request closed without merging**
