### PR TITLE
0401: misc improvements

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Hear ye, hear ye. This RFC is moving into **final comment period**.

**Comment by tshepang** [comment]
FCP for such superficial changes?

**Comment by nikomatsakis** [comment]
@tshepang I don't expect a lot of comments :) but we decided it's easier to just FCP everything.

**Comment by rkjnsn** [comment]
I object! (Okay, not really)

**Comment by nikomatsakis** [comment]
Unsurprisingly, we'll take this one. :) Thanks @tshepang !

**Pull request merged**
