### PR TITLE
Std::iter::once

### PR DESCRIPTION
**Pull request by XMPPwocky**
[Rendered](https://github.com/XMPPwocky/rfcs/blob/b30ad7141d43c7df0bac5ab76b1b5b0d1a735d9f/text/0000-std-iter-once.md)

### CODE REVIEW

**Comment by reem** [comment]
+1, I've wanted this before and disliked the IMO relatively ugly solutions.

**Comment by blaenk** [comment]
:+1: I think this would be nice. As the RFC states, and as I'm sure droves of people will be tripping over each other to point out, this thing is already possible in a variety of different ways. The point is that this would make the intent clear and its use concise. The most common trick used that I've seen is `Some(x).into_iter()`, but a dedicated function like `once` has the benefit of being easy to discover and document, which is useful for newcomers.

**Comment by pythonesque** [comment]
I don't really see what's wrong with the `Some(x).into_iter()` solution?  Other than discoverability, I suppose.

**Comment by XMPPwocky** [comment]
@pythonesque Discoverability, ergonomics, and looking strange (coming across it for the first time, it looks odd and you might be tempted to think it's an iterator over Option).

**Comment by reem** [comment]
When someone asks how to do this, `Some(x).into_iter()` is a trick, `iter::once(x)` is a solution (even if the implementation is the same).

**Comment by Ericson2314** [comment]
Let's just say I've written `//TODO factor out single element iterator` a few times :).

**Comment by bjz** [comment]
I made an issue about this before, but was discouraged: #437.

**Comment by kmcallister** [comment]
+1, I had to define this in html5ever to get reasonable APIs.

**Comment by drewm1980** [comment]
Could you add some examples where this is useful to the RFC?  I've done at least some stuff with iterators and have never run into this.  It is non-obvious to me why iterators are even relevant if you've only got one thing.

**Comment by drewm1980** [comment]
bikeshedding on the name, iterators (and only iterators?) yield things.  If you want and iterator that yields a value once, how about:

somevalue.yield_once()?

**Comment by Gankro** [comment]
Adding a method on every single value type is unacceptable.

**Comment by blaenk** [comment]
> It is non-obvious to me why iterators are even relevant if you've only got one thing.

@drewm1980: For example, in one of my library's tests I perform a globbing operation to get a list of paths to fixtures, but there's one fixture in a non-standard location (beyond my control), so what I do is I get the iterator for the glob, then I chain onto it the single extra path, so that then I can iterate over the composed iterator as one thing, instead of iterating over the glob, then doing it again only for the extra path that wasn't present in the glob results.

Keep in mind this is just one example of many. Perhaps you have some code that operates on iterators, but you only have one item, so you create an iterator consisting solely of that item.

**Comment by bjz** [comment]
> It is non-obvious to me why iterators are even relevant if you've only got one thing.

It is useful when chaining together iterators.

**Comment by XMPPwocky** [comment]
This could *potentially* replace `std::iter::repeat` with `std::iter::once().cycle()`; whether that is desirable is undecided.

(You can't replace this with `repeat`, since repeat needs a Clone bound, while `once` does not.)

**Comment by kmcallister** [comment]
@drewm1980

> It is non-obvious to me why iterators are even relevant if you've only got one thing.

html5ever accepts an iterator of `String`s, to support incremental parsing. But this kind of ruins the syntax for the common case of parsing a whole document, if we don't have something like `once`.

**Comment by aturon** [comment]
+0.5. 

While `Some(x).into_iter()` is usable for this I think it's a natural thing to have alongside other "leaf" combinators like `repeat` and `count`. I don't see a lot of downside to growing the API in this way.

(I do suspect that if we add this, we'll want `iter::empty` or some such as well.)

**Comment by drewm1980** [comment]
Thanks for the example use cases guys. RE iterator chaining, don't iterators already chain nicely by design?  Are there API's taking iterators of iterators that force you to increase the level of iteratorness in the middle of the chain?

**Comment by drewm1980** [comment]
Anyway, +1 if it's not in the prelude, or if it's in the prelude with a name that at least hints it's related to iterators, i.e. "yield_once" or something.  Is "yield" is already reserved as a keyword, perhaps for future pythonic ways of making generators/closures?

IMHO, "once" alone is too generic for the prelude; at first guess I would expect it to call a closure without using () syntax, like the "twice" example from the docs:

http://doc.rust-lang.org/book/closures.html#accepting-closures-as-arguments

**Comment by nikomatsakis** [comment]
:+1: I've wanted this from time to time for certain.

**Comment by erickt** [comment]
+1 to this and @aturon's `iter::empty()`. I don't think `iter::repeat(x).take(1)` works here as it'll only work with `Clone` types. I don't think we need to have explicit variants for `&T` and `&mut T`, we could always just call `once(&x)` to produce iterators of those types.

**Comment by brson** [comment]
lgtm

**Comment by steveklabnik** [comment]
:+1:

**Comment by aturon** [comment]
We've got a lot of enthusiasm for this RFC, but before we merge, I wonder: is it worth adding `empty` at the same time? (Seems reasonable to include both variants of the `Option` iterator.)

**Comment by huonw** [comment]
Do we want the name `once` & `empty`? It feels to me that the matching words would be `once` and `never`. The mismatch I see now is that `once` describes how often the element will be yielded, but `empty` describes the state of the iterator. (A small nitpick...)

**Comment by kmcallister** [comment]
`iter::one` and `iter::none`?

**Comment by aturon** [comment]
How about `one` and `empty`?

**Comment by seanmonstar** [comment]
One and zero? Or empty seems fine. Problem with one and none is its only 1
char difference...

**Comment by tshepang** [comment]
@seanmonstar I'd be very surprised to see someone do such a typo. I mean, I didn't even notice they were that close... they look very distinct.

**Comment by XMPPwocky** [comment]
@tshepang They'd also have different signatures.

````rust
std::iter::one(42);
std::iter::none();
````

**Comment by seanmonstar** [comment]
Good point, I retract my comment.

**Comment by ogham** [comment]
I actually found out about the `Some(x).into_iter()` idiom from this thread just now.

**Comment by aturon** [comment]
@XMPPwocky Can you update the RFC with `empty` as well? Otherwise, it's ready to be accepted at this point.

**Comment by XMPPwocky** [comment]
@aturon Done. Sorry, email from GitHub found its way into the great Gmail tab of spammy mailing lists, for some reason.

**Comment by aturon** [comment]
Thanks @XMPPwocky!

After getting stalled on some bikeshedding and lost emails, this RFC (which always has strong support) has been merged at last!

**Pull request merged**
