### PR TITLE
Add replace and swap functions to RefCell

### PR DESCRIPTION
**Pull request by notriddle**
[Rendered](https://github.com/notriddle/rust-rfcs/blob/refcell_replace/text/0000-refcell-replace.md)

### CODE REVIEW

**Comment by TimNN** [comment]
Would `try_replace` and `try_swap` be added as well, analogous to `try_borrow` and `try_borrow_mut`?

**Comment by notriddle** [comment]
That's not part of the RFC.

Since the only way you can make the swap and replace functions trigger is by doing them at the same time as a borrow, I don't think you need the try variants that often.

**Comment by aturon** [comment]
This looks great! I'm going to go ahead and propose to merge.

@rfcbot fcp merge

**Comment by dtolnay** [comment]
@rfcbot reviewed

**Comment by alexcrichton** [comment]
Ok looks like not much new discussion came up during FCP, so merging! I've opened a tracking issue at https://github.com/rust-lang/rust/issues/43570. Thanks again for the RFC @notriddle!

**Pull request merged**
