### PR TITLE
RFC: Macro syntax to count sequence repetitions

### PR DESCRIPTION
**Pull request by lilyball**
[Rendered view](https://github.com/kballard/rfcs/blob/79dd7ab943c45db7705cd7a972b2dcb7b6d0267b/active/000-count-macro-repetitions.md)

### CODE REVIEW

**Comment by Stebalien** [comment]
> Yeah, your `arity!()` macro can't handle `arity!(None, Some(_))`, because it thinks it's doing expressions and I really wanted patterns.

@kballard for completeness, that's easily fixed. The following seems to work for everything but item and meta (it allows mixed lists but there shouldn't be any ambiguity):

```rust
macro_rules! arity {
    ($e:tt, $($toks:tt)+) => { 1 + arity!($($toks)+) };
    ($e:tt) => { 1 };

    ($e:pat, $($toks:tt)+) => { 1 + arity!($($toks)+) };
    ($e:pat) => { 1 };

    ($e:expr, $($toks:tt)+) => { 1 + arity!($($toks)+) };
    ($e:expr) => { 1 };

    () => { 0 };
}
```

**Comment by alkis** [comment]
@kballard are you still pursuing this? I am in need of the repetition index in some macros I am writing and there is currently no way of getting this in the current state of macros. Is the discussion done here folded into some other rfc that would provide such functionality in some other way? Or do you have plans of pursuing this rfc further?

**Comment by Stebalien** [comment]
@alkis it's possible but you need to use recursion (you can't do it with the `$(...)*` syntax).

**Comment by alkis** [comment]
@Stebalien if you use recursion the repetition index will not be a literal but an expression. The index of the N'th item will expand to something like 0 + 1 + 1 + ... + 1. If you want the index to be used for accessing an element of a tuple unfortunately an expression won't work. AFAIK only a literal works.

**Comment by Stebalien** [comment]
@alkis I see. No, this doesn't work with tuples etc.

**Comment by alkis** [comment]
So what needs to be done to advance this RFC?

**Comment by bwo** [comment]
is this rfc abandoned? superseded?

**Comment by SimonSapin** [comment]
I think procedural macros https://github.com/rust-lang/rust/issues/38356 will make this largely unnecessary.

**Comment by Stebalien** [comment]
@SimonSapin Procedural macros are generally a heavy-weight solution and counting is something I've needed quite often in declarative macros (although building a `0 + 1 + 1 ...` expression is usually sufficient).

**Comment by SimonSapin** [comment]
At least building this as a procedural macro outside of the standard library would make it easier to make a case for inclusion in `std` in a new RFC.

**Comment by Stebalien** [comment]
Oh, I see. Good point!

**Pull request closed without merging**
