### PR TITLE
Shorten the `cargo` command

### PR DESCRIPTION
**Pull request by mark-i-m**
[Rendered](https://github.com/mark-i-m/rfcs/blob/46a74a9a204ac3879accecdb702cd27266d53a2b/text/0000-cargogo.md)

### CODE REVIEW

**Comment by Centril** [comment]
Clearly the new command should be named `cg`!

**Comment by crlf0710** [comment]
Can `cargo` work independently of toolchain? I mean, can we just 1. rename `cargo` to something else. 2. rename `rustup` to `cargo` ?

**Comment by warlord500** [comment]
I am definitely against this! while cargo is long for its high usage but I would like to remind ever one of common command used just like cargo, the great make command! in most modern operating systems, you have support for either alias and/or symbolic links and/or hard links and/or scripts making this change near useless.

for the hypothetical case that you are not  running on system with that support, you can likely cross compile to that machine using one of the above methods.

in addition, this change could lead to large amounts of confusion. people have to figure out if some one is referring to go(the language), (the compiler), (rust build tool for package management), and possibly more uses of "go". 

any shorter word will likely have the same problem as "go".

**Comment by est31** [comment]
I think we should call it ar instead. Go is already taken.

**Comment by gerryxiao** [comment]
Should be 'car', more pleasure to use really.

**Comment by nox** [comment]
Cars pollute and make people lazy, I think it should be named bike, which is still a 20% size improvement of the name. Then we can rename rustup to shed, which is a 33% size improvement too.

**Comment by sgrif** [comment]
I think we can all agree that there's no possible downside to using `go` for this command. Clearly this needs to be nominated for the next release

**Comment by Centril** [comment]
@nox In honor of Haskell Curry, I propose we rename `cargo` to `B` and `rustup` to `S`; And so then we have b & s.

**Comment by bluetech** [comment]
This is missing the [Prior Art](https://github.com/rust-lang/rfcs/blob/master/text/2333-prior-art.md) section. Of course, there isn't any.

**Comment by sgrif** [comment]
April 1 was a fun day. :smile:

**Pull request closed without merging**
