### PR TITLE
Add `maybe!` macro equivalent to `try!`

### PR DESCRIPTION
**Pull request by hauleth**
[Rendered](https://github.com/hauleth/rfcs/blob/try-some-macro/text/0000-try-some-macro.md)

### CODE REVIEW

**Comment by cassiersg** [comment]
For reference, there also exists a [try_opt crate](https://crates.io/crates/try_opt) that does the same thing as soma.

**Comment by hauleth** [comment]
@cassiersg I wasn't aware that this already exist. :+1:

**Comment by Ticki** [comment]
See also #243

**Comment by 4xrsJCr9** [comment]
Please consider renaming this macro to 'maybe'.

**Comment by reem** [comment]
Some alternatives: `Option::and_then` or `try!` with `Option::ok_or`/`Option::ok_or_else` depending on what's appropriate.

**Comment by alexcrichton** [comment]
:bell: This RFC is now entering its week-long **final comment period** :bell:

The libs team feels that we are likely to not merge this for now in light of [trait-based exception handling](https://github.com/rust-lang/rfcs/blob/master/text/0243-trait-based-exception-handling.md) having recently landed. We're likely to change `try!` to simply become `?` in which case this may mesh more nicely with `catch { ... }` as proposed there.

**Comment by daboross** [comment]
I feel like this doesn't really need to be a part of the standard library, as it has a lot smaller use case than try! does. I mean it wouldn't be *too* bad to add it, but it might just be extra bloat.

**Comment by skade** [comment]
I would strongly avoid naming the macro `maybe!` for similarity with the type of the same name in other programming languages. Rust uses `Option` instead of `Maybe`, `maybe!` sounds like diverging from that.

**Comment by k3d3** [comment]
Having something that deals with Options being called `maybe!` is confusing IMO - it should be called `some!`, `option!`, or `opt!`.

**Comment by nrc** [comment]
I strongly want a facility for doing this and in the past I've argued for a macro (so many projects have their own for doing this!), however, it seems the best way forward now is to make `?` work with `Option`, so I think we should not accept this RFC (I also don't like `maybe` as a name, fwiw) and push on getting `?` to support `Option` asap.

**Comment by alexcrichton** [comment]
The libs team discussed this RFC during triage yesterday and the conclusion was to close (in the face of trait-based exception handling). Thanks again though for the RFC @hauleth!

**Pull request closed without merging**
