### PR TITLE
Feature gate extern fn methods

### PR DESCRIPTION
**Pull request by Aatch**
[Rendered](https://github.com/Aatch/rust-rfcs/blob/extern-fn-methods/text/0000-extern-fn-methods.md)

### CODE REVIEW

**Comment by nagisa** [comment]
SGTM.

**Comment by rphmeier** [comment]
This seems very reasonable, but I'd be interested in seeing the fallout. Are there a lot of bindings to C libraries which use this feature?

**Comment by nagisa** [comment]
I know we have received at least one bug report about this feature in conjunction with `no_mangle` once our symbol duplication detection has landed.

**Comment by RalfJung** [comment]
Doesn't this RFC effectively break all Rust crates that wrap C libraries, e.g. <https://crates.io/crates/openssl-sys/> and <https://crates.io/crates/libusb-sys/> and [many more](https://crates.io/search?q=-sys)?

**Comment by remram44** [comment]
@RalfJung No it doesn't. This RFC only aim to feature-gate extern *methods*, not functions.

**Comment by RalfJung** [comment]
Oh, I see :)

**Comment by nikomatsakis** [comment]
@Aatch do you have an impl? if you can whip one up, I can do a crater run, feels like necessary data before we make a decision one way or the other. But I'm inclined to :+1: here.

**Comment by nrc** [comment]
Vaguely related, should rustfmt change `extern` to `extern "C"` or vice versa: https://github.com/rust-lang-nursery/rustfmt/issues/451

**Comment by nrc** [comment]
And +1 for a crater run

**Comment by eddyb** [comment]
This is no longer necessary AFAIK, all methods should be compatible with all ABIs now.

**Comment by nikomatsakis** [comment]
**Hear ye, hear ye!** This RFC is now entering **final comment period**.

I should note that, personally, I'm inclined not to accept, based on @eddyb's comment.

**Comment by nikomatsakis** [comment]
After discussion in the @rust-lang/lang meeting today, we've decided not to accept this RFC. There doesn't seem to be any particular semantic concerns about allowing methods to have their own ABI, and the implementation is even working as far as we know, so retroactively feature gating is not necessary. Thanks @Aatch!

**Pull request closed without merging**
