### PR TITLE
RFC: add prefetch intrinsics

### PR DESCRIPTION
**Pull request by jbalintbiro**
[rendered view](https://github.com/saati/rfcs/blob/master/active/0000-prefetch-intrinsics.md)

### CODE REVIEW

**Comment by fanf2** [comment]
There are cases where prefetching can be an enormous benefit to tree structures - e.g. https://dotat.at/prog/qp/blog-2015-10-11.html

The tl;dr is you can benefit from prefetching when there is a nontrivial calculation to choose a child node, and you can put the metadata required for the calculation in the parent adjacent to the node pointer instead of inside the node itself, so that you can prefetch the node contents while working out the child's offset within the node.

**Comment by fanf2** [comment]
Another example of prefetch improving performance, for several array  search algorithms - https://arxiv.org/abs/1509.05053

**Comment by jonhoo** [comment]
Following up on @fanf2's comment above, this is relevant for https://github.com/jonhoo/ordsearch, which implements the fast data-structure from the linked paper. It currently depends on the [prefetch](https://github.com/aweinstock314/prefetch) crate, which is nightly-only.

**Comment by jrmuizel** [comment]
@jonhoo how much of a performance difference does prefetching make for ordsearch?

**Comment by jonhoo** [comment]
See Figure 10 of https://arxiv.org/pdf/1509.05053.pdf for the impact on regular binary search, and Figure 11 for the impact on the algorithm used by ordsearch. Speedup is ~2x.

**Comment by alkis** [comment]
Prefetch can make a huge difference with hashtables as well (prefetch the slot for a key you are going to need soon).

That said, software prefetching is extremely hard to use and get right. Current CPUs are so good at prefetching so beating them is hard and also even across the same line of CPUs (intel for example) prefetch doesn't behave the same way across all models (pre-Skylake/post-Skylake have some dramatic differences).

**Pull request closed without merging**
