### PR TITLE
Blueprints

### PR DESCRIPTION
**Pull request by DasLixou**
I am not that experienced with RFCs, feedback welcome 😀

[Rendered](https://github.com/DasLixou/rust-rfcs/blob/DasLixou-blueprints/text/3422-blueprints.md)

### CODE REVIEW

**Comment by shepmaster** [comment]
> So I wrote a little experiment in godbolt and saw that a new function described as below results in a function with a call

Did you compile with optimizations? `-C opt-level=2`. When I add that, it produces

```
example::main:
        ret
```

**Comment by DasLixou** [comment]
> > So I wrote a little experiment in godbolt and saw that a new function described as below results in a function with a call
> 
> Did you compile with optimizations? `-C opt-level=2`. When I add that, it produces
> 
> ```
> example::main:
>         ret
> ```

Because it is never used. But a good point... I'll look how it behaves when using optimization

**Comment by DasLixou** [comment]
Yeah, you are right. It gets optimized away even without a mention of inline. But i think in some cases it's still good to have it explicitly declare that you want to blueprint it

**Comment by shepmaster** [comment]
> But i think in some cases it's still good to have it explicitly declare that you want to blueprint it

That's the point of the `inline` attribute. How is `#[blueprint]` any different?

**Comment by DasLixou** [comment]
> > But i think in some cases it's still good to have it explicitly declare that you want to blueprint it
> 
> That's the point of the `inline` attribute. How is `#[blueprint]` any different?

Oh. I was confused by inline and inline(always) and that inline didnt do anything so i thought it was for something else.

So should i close this?

**Comment by SOF3** [comment]
As you said in the RFC, `inline(always)` already does the trick. So what is the difference from `inline(always)`?

Furthermore, inlining is not always cost-free. Increasing the size of a function could increase cache miss on (especially low-end) CPUs and result in worse performance for inlining cold paths.

**Comment by DasLixou** [comment]
Ok then ill close this

**Pull request closed without merging**
