### PR TITLE
Add "Integers Done Right" RFC.

### PR DESCRIPTION
**Pull request by michaelwoerister**
[Rendered View](https://github.com/michaelwoerister/rfcs/blob/integers/text/0000-integers-done-right.md)

### CODE REVIEW

**Comment by nikomatsakis** [comment]
:+1: Finally, a proper fix!

**Comment by reem** [comment]
When I opened this document on my phone, it's radiance burned out my phone screen! I can only conclude that this is the best choice, moving forward.

**Comment by norcalli** [comment]
Could you please post the bit size table in nibbles? It's harder to read otherwise. I.e. `signed short u8 = 1.25 nibbles`.

**Comment by bstrie** [comment]
This approach is not just incredibly myopic, but unbelievably shortsighted as well. Remember that C is the *third programming language ever invented*, as evidenced by the fact that they had not yet exhausted even the space of single-digit language names (thereby placing it among the [first generation programming languages](http://en.wikipedia.org/wiki/First-generation_programming_language)). RUST, as a [fourth-generation language](http://en.wikipedia.org/wiki/Fourth-generation_programming_language) and the heir apparent to RUSS, can do better than seek such Methuselian influence. We should be looking *ahead*, not behind, to the [fifth generation](http://en.wikipedia.org/wiki/Fifth-generation_programming_language), at such languages as Apple's revolutionary SWIFT. Behold, SWIFT's dazzlingly bold assortment of integral types:
```
Uint
Uint8
Uint16
Uint32
Uint64
Int
Int8
Int26
Int32
Int64
```
Take a moment to catch your breath, if needed. Place your hand on a stool to steady yourself, close your eyes, count to a power of two. Such unparalleled clarity in language design comes around but once in a generation. To survive, Rust must ride the coming wave of modernity and *co-opt* these types as its own.

Look, here is but the merest of your examples rewritten with such Terpsichorean grace as this provides:
```rust
/// Return the absolute of the maximum of two values
fn abs_max( a: signed long Uint8 i32,
            b: signed long Uint8 i32 )
            -> unsigned long Int16 u64 {
    // Take the greater of the two values
    let max = if a > b {
        a
    } else {
        b
    };
```
*Can there be any doubt as to its ascendance?!*

**Comment by yndi** [comment]
Jeez, you got me. You can't even imagine how many times I mumbled "wtf?!" while reading the RFC. It's already midnight in here.

**Comment by steveklabnik** [comment]
> Could you please post the bit size table in nibbles?

nit: nybble forever

**Comment by shepmaster** [comment]
While this is a good start, it's missing a few core points. The Rust style is to uppercase type names, so these should be renamed to `U32` and `I8`, and so on. 

SIMD types are completely neglected in this proposal, which indicates the author **clearly** didn't think about performance. Please refer to the FORTRAN manual for a reference to get started. 

Also, please take this opportunity to fix floating point numbers. Remove NaN and infinity, those have proven to be too error prone. In addition, support numbers like 0.3. Not supporting this is an obvious bug and shows our disdain for any kind of testing.

**Comment by shepmaster** [comment]
@steveklabnik

I think you mean

> nyt: nybble forever

**Comment by shepmaster** [comment]
@bstrie

> Int26

The majesty is overpowering.

**Comment by bstrie** [comment]
@shepmaster Keep me appraised of whether you would like to borrow my vial of smelling salts, to ease the lightheadedness.

**Comment by wolenber** [comment]
I really, really don't like `signed` and `unsigned` prefixes. They add so much complexity for almost no gain.

But +1 for `short` and `long`

**Comment by theypsilon** [comment]
The keywords are way too long, we should use trigraphs instead, also present in those world wide known languages. I.e. for unsafe overflow: ó_ò i32

**Comment by grissiom** [comment]
Does `signed u32` make any sense? It sounds like "I have a unsigned 32 bit integer, which is signed..."

**Comment by bvssvni** [comment]
+1 We need this in Piston.

**Comment by JanLikar** [comment]
I'm new to Rust, but I feel this RFC adds overly compex features.

**Comment by Ygg01** [comment]
@JanLikar What's so complex about

      signed unsigned types like signed long u64 need one bit more in order to store their sign. In the  
      unlikely case that this leads to memory alignment issues, the recommended implementation strategy 
      is to pad up to the next prime, or if need be, pool the additional bits in the cloud or on floppy disk.

?

It's like you think this is some elaborate prank.

**Comment by oli-obk** [comment]
I want this for my own types. Not just the builtin types.

```rust
struct MyType(i32);
struct unsigned MyType(String);
```

**Comment by shepmaster** [comment]
> I want this for my own types

This makes sense, but I don't want to have to duplicate my code for different signed-ness. Can we introduce HKS (Higher-Kinded Signedness) to improve the ergonomics and reduce programmer burden?

**Comment by aochagavia** [comment]
I really thought this was real for a while... Pretty relieved to discover it is a joke!

**Comment by oli-obk** [comment]
> I really thought this was real for a while... Pretty relieved to discover it is a joke!

You should be ashamed of yourself to make jokes about such a great proposal!

**Comment by grissiom** [comment]
On Thu, Apr 2, 2015 at 5:47 PM, Felix S Klock II <notifications@github.com>
wrote:

> @grissiom <https://github.com/grissiom> wrote :
>
> Does signed u32 make any sense? It sounds like "I have a unsigned 32 bit
> integer, which is signed..."
>
> The RFC addresses this.
>
> e.g.:
>
> signed unsigned types like signed long u64 need one bit more in order to
> store their sign. In the unlikely case that this leads to memory alignment
> issues, the recommended implementation strategy is to pad up to the next
> prime, or if need be, pool the additional bits in the cloud or on floppy
> disk.
>
>
Yes, I've seen this. So:

1, Are `signed u32` and `u32` different types or just the same type with
different "qualifier"?
2, If they are the same type, every `u32` will consume at least 33bits,
right?
3, If they are not the same type, calling `fn func(a: u32) -> u32` with
`signed u32` will fail to compile, right?

**Comment by Ygg01** [comment]
@grissiom It's simple:

1. `signed u32` and `u32` are same types but with different values, stored inside wetware storage unit under same value but different type, move en-triplicate, buried and turned into cigarette matches distributed at night clubs.
2. Every  `u32` type only consumes as much A̯̪͆͆s̝̩̗̬̯ͅ ̹̥̞̱̄̍T̙̩̟h̖̪́e̷̺͈̣̞̜͕͆̓̄ͤ̈ͅ ̞̯ͧ̇̈̑ͬ̈̋Õ̦̺̣̬͛͞n̵̩̟͕̳̎ͩͭͥ̂̑̚e̸̯̰͙̼̰̬ ̻̗̦̜͗T̪͙͇̥ͦ̔h͈̣̫̻̫̅͌̏̏å̳̖ͥ̀̉̌ͭͮt ̴̥̪͚͖ͥ͑͐̿̋W̰̰̺͖̞̮̄͆̒̃̎͞ḁ͓̪͓̈t̤̜̟̰̲̟ͩ̾̉ͧͅc̟̘͍̳̲͔̩̐ͩͧ͛͗̚h̛̖̖̳̉͆̃es̷̱͚̩̀ͮ̉̓̉͌ ͇̥͍̬̠͟O͕̩ͪ́u̽́̍̑͋̌ͮ҉̹͖̳t̡̖s̜̹̫͎̫ͣ͋ͅȉ͒͢d͍̖̪̟̫̩̅e̱̯̺̙͕̻ͪ̿ͭ͂̋ͥ͠ ͂̒͌̊̕W̝̟̳͍̥͎̻͝i̥̯̩̓ͅśͮ̎ͫh̰͖̟̥͎̞̀ͣͯͩȇ̢̹͖͚̲̒̎ͯͧ͛̋ṡ̛͍̥͓͓̜̝͙̈̂ͩ͒̐̒ ̵ͩ͆̍̇ͪͬ̐I̤͋̆̈́t͇̏̄ͣ̊͝ ̪͙̹̝͂ͥͮ̾͂̍͝ͅc̨̳̗̠̖̝͛ͬ͌̅̄̈ǫ̘͖̗͚̳͖̯̌̿͂̑n͎͚̖̗̻ŝ̡̰̼̘̼̮̥͔̏̾̉u̵̥͈̗m̳̘̳̱̥̻̰̃ͮͤ̌̎̓̚e̼̙̙̰̖ͤ͡.̼̫ͦ


3. Failure only happens if you meet a dark end.

**Comment by kvark** [comment]
I'm totally with @bstrie here. The less complexity, the better. Our current scheme of things with `usize/isize` is pretty good.

**Comment by pnkfelix** [comment]
Okay I think it is no longer April 1st anywhere on the globe; I'm going to close this PR, as much fun as it might be to let it sit out as a honey-pot.

**Comment by michaelwoerister** [comment]
> I'm going to close this PR...

I've decided anyway that it would be unwise to jeopardize my bright future as a programming language designer by wasting all my good ideas on other people's languages, so please consider this PR closed before you closed it. Thanks.

**Comment by Ticki** [comment]
It's sad such a great RFC is just unfairly closed.

**Pull request closed without merging**
