### PR TITLE
Remove the `proc` keyword from the language

### PR DESCRIPTION
**Pull request by crumblingstatue**
[Rendered](https://github.com/crumblingstatue/rfcs/blob/master/text/0000-remove-proc-keyword.md)

### CODE REVIEW

**Comment by kennytm** [comment]
A little off-topic, but it seems `be` is [still a keyword](https://github.com/rust-lang/rust/blob/0c96037ec1676b420002a06ea337865f95abbf2c/src/libsyntax/parse/token.rs#L566) albeit being removed long time ago in rust-lang/rust#2227.

**Comment by nikomatsakis** [comment]
Sounds good to me! I think the fact that `proc` is still there was basically an oversight.

**Comment by tioover** [comment]
@kennytm  `be` is reserved word...

**Comment by alexcrichton** [comment]
Thanks for the RFC! We talked about this today and we think this is fine to do, but it doesn't necessarily need an RFC. Feel free to submit a PR implementing this!

**Pull request closed without merging**
