### PR TITLE
Add if-while-let_multiple_patterns RFC

### PR DESCRIPTION
**Pull request by Munksgaard**
This has already been implemented in rust-lang/rust#23034

### CODE REVIEW

**Comment by Munksgaard** [comment]
cc @Manishearth, @pcwalton

**Comment by laumann** [comment]
[Rendered](https://github.com/Munksgaard/rfcs/blob/master/text/0000-if-while-let_multiple_patterns.md)

**Comment by Munksgaard** [comment]
Discussed in #935

**Comment by Gankro** [comment]
Should this RFC also propose that exhaustive `lets` should also work? It seems like that's the last place where `|` wouldn't work, which is sort of random.

e.g.

```
fn main() {
    let x: Result<u32, u32> = Ok(1);
    let Ok(y) | Err(y) = x;
    println!("{}", y);
}
```

**Comment by Kimundi** [comment]
@Gankro: I agree that that would be more consistent, but I think that would make more sense to open as a seperate RFC.

Alternatively, a RFC could change `PAT | PAT` in general to become a pattern, which would make both `ìf let`, `while let`, `let` and function arguments be able to use the `|` form.

**Comment by Munksgaard** [comment]
@Kimundi: The more general approach (eg. also allowing alternations (`|`) in function arguments) has been discussed a bit in #99.

I hadn't considered alternations in normal `let`s, but I guess we could create another RFC for that case?

**Comment by Manishearth** [comment]
I would opt for a separate RfC for that.

**Comment by Manishearth** [comment]
(I agree with this RfC, btw)

**Comment by glaebhoerl** [comment]
> We could consider extending `if let` and `while let` to also include guards, but that has opens up the question about syntax (`if let Some(n) = x if n > 0` is not extremely pretty), so we should probably save that for an RFC of its own.

In fact if we also `if let` as the syntax for Haskell-style [pattern guards](https://github.com/rust-lang/rfcs/issues/680), then it seems like we could end up with `if let Some(b) = a if let Some(c) = b`, which is even more awesome, in a very particular sense. (This seems to also be an infinite regress?)

**Comment by pcwalton** [comment]
@glaebhoerl Couldn't all of those be written with `@` (e.g. `if let Some(b @ Some(c)) = a`?

**Comment by glaebhoerl** [comment]
@pcwalton Sure; I only meant to point out that if we change the `if let` expression to allow guards, and also generalize guards to allow pattern guards with the syntax `if let`, then a pattern guard on an `if let` would result in `if let ... if let`. This actually feels *logical* to me, but could also be considered unusual. The example was just to illustrate the syntax. (tl;dr it's not at all an objection on my part, just an observation)

**Comment by Munksgaard** [comment]
> In fact if we also use if let as the syntax for Haskell-style pattern guards (which I think would be logical), then it seems like we could end up with if let Some(b) = a if let Some(c) = b, which is even more awesome, in a very particular sense. (This seems to also be an infinite regress?)

That's a very interesting question, and it doesn't seem like it would hurt the language as such. However, this seems like an orthogonal issue.

**Comment by Munksgaard** [comment]
What's the verdict on this? Most people here and in #935 seem to be in agreement that this is a useful addition to the language, but it also opens up various questions regarding additional constructs such as nested `if let`s and guards. Most of those questions/suggestions represent larger additions to the language, whereas I feel like the feature proposed in this particular RFC has more straightforward implications.

**Comment by brson** [comment]
@Munksgaard my inclination is that this is a nice-to-have feature that we don't need presently. It's very tempting to add to Rust every nice convenience, but we have to exercise restraint.

**Comment by kballard** [comment]
I'm not convinced that this is something we should do. In general, I'm in favor of making `if let` more powerful, but I'm concerned that making changes like this right now will prevent us from doing other useful stuff in the future.

For example, `if let` was inspired by Swift, and Swift 1.2 extends `if let` with some useful functionality that we don't currently have an analogue for in Rust, which is basically chained expressions. In Swift 1.2 you can say something like:

```swift
if let a = foo(), let b = a.bar(), let c = b.baz() where c > 2, let d = c.quux() {
    // do something with d
} else {
    // some expression in that chain failed
}
```

(this can actually be shortened slightly by dropping the 2nd and 3rd `let`s, it's only required on chained expressions after a `where` clause)

This is equivalent to

```swift
var success = false
if let a = foo() {
    if let b = a.bar() {
        if let c = b.baz() where c > 2 {
            if let d = c.quux() {
                success = true
                // do something with d
            }
        }
    }
}
if !success {
    // some expression in that chain failed
}
```

This turns out to be a useful construct, and I'd like to eventually get something similar into Rust. But if we loosen the `if let` syntax today, it's not clear if that will interfere with the ability to extend the syntax like this in the future.

More generally, making changes to make `if let` be able to do more stuff that `match` can do just seems like something being done for the sake of doing it. If you want to do stuff that `match` can do, then go ahead and use `match`. `if let` today is just a convenience for a simple form of `match`, but there's no reason why it needs to be equivalent to a single `match` in the future.

**Comment by mdinger** [comment]
@kballard That seems similar to https://github.com/rust-lang/rfcs/issues/929 which used `&&` instead of commas, though where clauses never occurred to me.

**Comment by mahkoh** [comment]
>For example, if let was inspired by Swift

**Comment by mahkoh** [comment]
https://github.com/rust-lang/rust/issues/1529

Credit goes to @kballard

**Comment by kballard** [comment]
@mahkoh I wrote the `if let` RFC. It was directly inspired by Swift. I can believe that a similar concept was talked about internally at Mozilla before then, but if so, it was never made publicly known.

**Comment by mahkoh** [comment]
That just means that the RFC was inspired by swift. The idea to destructure in `if` is much older. It might even be so that someone working on swift got the idea from the linked issue.

**Comment by mahkoh** [comment]
To contribute something on-topic: I share @kballard's concerns. The following constructs seem interesting too and one would have to think about how they interact with this RFC:

```rust
if let Some(x) = x1 || let Some(x) = x2
if (let Some(ref x) = x1 && x > 0) || let Some(ref x) = x2
```

**Comment by brson** [comment]
Although this is a cool feature, per general concerns about feature creep, I'm closing this RFC without accepting it. Thank you.

**Pull request closed without merging**
