### PR TITLE
Implement Add for OsString

### PR DESCRIPTION
**Pull request by Rufflewind**
Add `Add` to `OsString`.

[Rendered](https://github.com/Rufflewind/rfcs/blob/os-string-add/text/0000-os-string-add.md)

### CODE REVIEW

**Comment by ubsan** [comment]
I don't like the `+` implementation for `String`, but as long as it exists it seems reasonable to have these implementations for `OsString`.

**Comment by BurntSushi** [comment]
I think this RFC is lacking detail. Here are some questions that I expect to see answered in the RFC itself:

* An implementation on `Add` seems to encourage allocating new `OsString` values over mutating existing ones. How important is this draw back?
* What examples from real code benefit from this change?
* The "How We Teach This" section is basically non-existent. I don't think "users already know it so we don't need to teach it" is an acceptable answer. For example, do we start encouraging people to use `+` for `OsString` as an idiom? How do we balance it with the trade offs of using `push`?
* Why aren't we also implementing `AddAssign`?
* If we add `Add` impls for `OsString`, does that mean we should add `Add` impls for `PathBuf` too?
* If we don't like the `Add` impls on `String`, does it still make sense to add new `Add` impls for other string-like types?

**Comment by Rufflewind** [comment]
> Unfortunately, I think this RFC is lacking detail.

It was intentionally short, given that:

- it is 7 lines of code
- it mirrors the existing `String` API
- it was presumed that the absence of `Add` was only an omission
- it does not impose any new semantics on `OsString` because `push` already exists

I was not previously aware of the controversy over `Add` for `String`.

> An implementation on Add seems to encourage allocating new OsString values over mutating existing ones. How important is this draw back?

`Add` does not encourage allocation any more than `.push` does, as the former is no more than a syntactic sugar over the latter that avoids the need for an intermediate mutable variable.

> Why aren't we also implementing AddAssign?

It can be included if there is demand.

**Comment by burdges** [comment]
I'd say deprecate the `+` for `String` and add a binary `++` operator called `MonoidAdd` or something.

**Comment by eddyb** [comment]
Why `MonoidAdd` when `Concat` or `Append` work quite nicely?

**Comment by burdges** [comment]
Yeah `Append` would be better, anyone who knows what a moniod is can figure out that they should be using it.

**Comment by le-jzr** [comment]
I'm partial to `Concat` over `Append`, but +1 either way.

With `Concat` that takes a slice of arbitrary size, instead of just two arguments, you could efficiently compile expressions like `a ++ b ++ c ++ d`, for which a regular binary operator would be very inefficient and deter users in favor of function calls.

**Comment by eddyb** [comment]
@le-jzr I'd use some sort of `HList` (tuples, ideally) to allow heterogenous concats (`Option<T>` and/or `Option<&[T]>` comes to mind).

**Comment by aturon** [comment]
@BurntSushi can we drive this toward a conclusion?

**Comment by BurntSushi** [comment]
Given the inactivity on this RFC, I move to close it. In general, I think whether this RFC is appropriate or not depends on whether we want to see the `Add` impl on `String` take over on other string types. I lean towards no. I think this change just doesn't carry its weight.

@rfcbot fcp close

**Comment by vks** [comment]
Does this imply `+` is going to be deprecated for `String` in some future epoch?

**Comment by Centril** [comment]
Closing since FCP with a motion to close is now complete.

**Pull request closed without merging**
