### PR TITLE
Extract math from Float trait

### PR DESCRIPTION
**Pull request by hauleth**
[Rendered](https://github.com/hauleth/rfcs/blob/split-num-float/text/0000-extract-math-from-float.md).

### CODE REVIEW

**Comment by Diggsey** [comment]
A single math trait doesn't make sense: the set of mathematical operations on floats is very different from those on integers, or even decimal or fixed point numbers.

**Comment by hauleth** [comment]
I agree that there should be more traits, but on the other hand we shouldn't go insane with splitting them just for having generic code for any numeric type. It should be [carefully evaluated](http://www.reddit.com/r/rust/comments/2xux1i/swift_madness_of_generic_integer/).

**Comment by aturon** [comment]
> It kind of reverse RFC #0369, but in my opinion it has been too radical which can be seen as num crate bring most of these traits back. This makes num crate kind of must have for any code related to math.

To be clear, the earlier RFC had this as an *explicit goal*:

> **Future-proofing for external numerics packages.** The Cargo ecosystem should ultimately provide choices of sophisticated numeric hierarchies, and `std::num` should not get in the way.

As that RFC discusses, there was a long history of changes to `std::num` and no consensus about what a solid numeric hierarchy would look like. That doesn't mean there will *never* be one in `std`, but like many other areas we are leaving it up to crates.io to develop a good set of candidates.

The role of the current traits is primarily just to provide methods on the primitive numeric types, because they [cannot be given inherent methods](https://github.com/rust-lang/rust/issues/16862).

**Comment by aturon** [comment]
The float trait [has been removed](https://github.com/rust-lang/rust/pull/23549) in favor of [inherent methods](https://github.com/rust-lang/rust/pull/23104). I'm going to close this RFC, since it no longer applies.

FWIW, generic programming over numeric types is a *very* important area of focus, but this is why we want to let a design bake in crates.io rather than freezing something suboptimal.

**Pull request closed without merging**
