### PR TITLE
Add new RFCs to list

### PR DESCRIPTION
**Pull request by pthariensflame**
Continuation of #1706.

@durka wanted some kind of automated mechanism for doing this; what would be the best way to accomplish that?

### CODE REVIEW

**Comment by ubsan** [comment]
Perhaps as part of merging a new RFC, add it to the README?

**Comment by durka** [comment]
@ubsan they're not merged during discussion, though.

**Comment by Ericson2314** [comment]
I thought "active" meant accepted but not yet implemented?

**Comment by pthariensflame** [comment]
@Erricson2314 It does mean that.

**Comment by Ericson2314** [comment]
Ok good. Then adding to the list on merge as @ubsan suggests will indeed work.

**Comment by nrc** [comment]
Actually, it would be nice to have a bit more tooling support for merging an RFC - it should be a one-click thing, but it is actually a pain - you often have to rename the file, check the 'header' details are correct. Add the PR link, file a tracking issue, add that link, then add the merged RFC to the list in README. This should all be doable by a bot. It would be a nice little project to write - would need to know about Git and GitHub, etc. If anyone wants to have a go at this I'd be happy to help out with advice on the various APIs, etc. And we have accounts for bots that we could use (rust-highfive, for example) which have the necessary privs.

**Comment by pthariensflame** [comment]
@nrc I would be more than happy to write a bot that does this!  I just need to ramp up into understanding the GitHub APIs.  :)

**Comment by nrc** [comment]
@pthariensflame let me know if you have any questions (probably irc is best, I'm nrc there too) - the GH APIs are not too bad to learn, once you get your head around the basic architecture. [Here](https://github.com/nrc/triage/tree/master/src) is an example of one of our bots - it handles triage on the main Rust repo, it is node.js, but should be pretty easy to see what the API calls are doing for a Rust bot.

**Comment by pthariensflame** [comment]
The repository which will eventually contain the bot is here:
https://github.com/chirex-machinens/RFC-stuff

**Comment by pthariensflame** [comment]
Updated in light of #1679 being merged.

**Comment by pthariensflame** [comment]
Updated again in light of #1681 being merged.

**Comment by alexcrichton** [comment]
Thanks for the PR @pthariensflame! We discussed this briefly in the core team meeting yesterday and the conclusion was that we're going to remove this section from the README which, as I'm sure you can tell, is updated in a very sporadic, if ever, fashion.

Perhaps if we [get more tooling](https://github.com/rust-lang/rfcs/pull/1714#issuecomment-239700425) we can re-add this section, but for now I'm gonna send a commit to remove it and close this for now.

**Comment by pthariensflame** [comment]
That's fine!  I feel like we can come up with a better interface to this information anyway.

**Pull request closed without merging**
