### PR TITLE
Add Cargo Templates

### PR DESCRIPTION
**Pull request by henryboisdequin**
## [🖼️ Rendered](https://github.com/henryboisdequin/rfcs/blob/master/text/0000-cargo-templates.md)

### CODE REVIEW

**Comment by RustyYato** [comment]
What's wrong with using [`cargo-generate`](https://lib.rs/crates/cargo-generate)?

**Comment by henryboisdequin** [comment]
> What's wrong with using [`cargo-generate`](https://lib.rs/crates/cargo-generate)?

There's nothing wrong with `cargo-generate`, maybe it would be better if it was already included in Cargo (I think it would be a larger ecosystem). Maybe a merge with `cargo-generate` would be better?

**Comment by kennytm** [comment]
Duplicate of #2922?

**Comment by henryboisdequin** [comment]
> Duplicate of #2922?

Oops, didn't see that RFC

**Pull request closed without merging**
