### PR TITLE
Reduce the number of constraints repeated when writing `T: SomeTrait`

### PR DESCRIPTION
**Pull request by sgrif**
[Rendered](https://github.com/sgrif/rfcs/blob/sg-visible-where-clause/text/0000-visible-where-clause.md)

### CODE REVIEW

**Comment by nikomatsakis** [comment]
There is a rustc bug on this issue as well:

https://github.com/rust-lang/rust/issues/20671

I am generally in favor of this change. I have to give the RFC a detailed read. I am not sure if there are backwards compatibility concerns -- if so I would expect them to arise only in corner cases, but still worth considering.

**Comment by durka** [comment]
Why leave the several exceptions where supertrait bounds would not be inherited? It seems less confusing to inherit everything.

In particular I don't understand the difference between `Vec<Self>: Bar` and `Result<Self, T>: Bar`.

**Comment by soltanmm** [comment]
When it says that `Self` appearing in the target means that the constraint will be inherited (elaborated?), does that include associated type projections (e.g. `Self::Foo: Trait`)? Either way, could that be explicitly mentioned?

**Comment by aturon** [comment]
@nikomatsakis Any thoughts on this? Are you inclined to subsume this under a more general implied bounds RFC? Can we mentor someone to write that?

**Comment by nikomatsakis** [comment]
I am going to close this RFC in favor of https://github.com/rust-lang/rfcs/pull/2089, which proposes a more general variant of the design described in here! But please, @sgrif or others, let me know if you see anything that this RFC covered that #2089 does not!

**Pull request closed without merging**
