### PR TITLE
Make mem::uninitialized() and mem::zeroed() const fn

### PR DESCRIPTION
**Pull request by Amanieu**
[Rendered](https://github.com/Amanieu/rfcs/blob/const_uninitialized/text/0000-const-uninitialized.md)

### CODE REVIEW

**Comment by nagisa** [comment]
I’m inclined to not do anything like this before we get const fn implemented proper, not hacked onto the ye olde const_eval.

**Comment by Amanieu** [comment]
Actually I think there is a better way of doing this by using unions:
```rust
union MyUnion<T> {
    data: T,
    no_data: (),
}

static X: MyUnion<T> = MyUnion { no_data: () };
```

So maybe this RFC isn't needed after all...

**Comment by Ericson2314** [comment]
@nagisa I'll agree based on how close miri is :).
@Amanieu I rather only use unions for FFI. They add zero safety here over the original RFC. And practically, I think unions are a longer way off.

**Comment by Amanieu** [comment]
The advantage of using unions is that it will cleanly handle `Some(uninitialized)` since the `no_data` in the union inhibits enum layout optimizations.

**Comment by Ericson2314** [comment]
Hmm? Aren't we getting rid of the option for the proposed usecase? What layout optimizations are there without a tag? I am really confused by that comment.

**Comment by rkjnsn** [comment]
@Ericson2314 My understanding is that with this RFC as proposed, it would be possible to do something like this:

```rust
static X: Option<&T> = unsafe { Some(std::mem::zeroed()) };
```

Because of the enum layout optimization, the final value of `X` at runtime would be `None`. The compiler would have to deal with this during compile-time constant evaluation.

Without this RFC, but with unions, one would instead write

```rust
static X: Option<MyUnion<&T>> = Some(MyUnion { no_data: () });
```

The union would inhibit the layout optimization, so the `Option` would have a tag, avoiding the corner case.

(Note that I don't think anyone would write either of these in actual code. The point is to demonstrate that the former introduces a compile-time corner case that the latter does not.)

**Comment by alexcrichton** [comment]
Thanks for the RFC @Amanieu! The libs team discussed this today and the conclusion was that this likely doesn't need an RFC, just a compiler implementation. That is, from the libs perspective, we're fine doing this any time. In light of that I'm going to close, but PRs are of course always welcome!

**Pull request closed without merging**
