### PR TITLE
Lose the tick

### PR DESCRIPTION
**Pull request by glaebhoerl**
[Impact in tee minus...](https://github.com/glaebhoerl/rfcs/blob/9182409b19acf586b965bbb4ffd979ac11a0b989/text/0000-lose-the-tick.md)

### CODE REVIEW

**Comment by tshepang** [comment]
[a discussion from last year in which no decision was made](https://github.com/rust-lang/meeting-minutes/blob/master/workweek-2014-08-18/lifetime-syntax.md)

**Comment by sinistersnare** [comment]
[a similar RFC, which was rejected](https://github.com/rust-lang/rfcs/pull/134).

It is too close to 1.0 to change this IMO. I also do not like any of the proposed syntaxes for annotating references themselves.

-1. I like the thought that we should move to a more pythonic approach of using keywords over sigils, but i feel like this should stay. :)

**Comment by tshepang** [comment]
[another discussion](http://discuss.rust-lang.org/t/lifetime-notation/751/18)

**Comment by blaenk** [comment]
I wouldn't mind this, I'd say I'm more or less indifferent. If we did do this though, I think the first syntax is by far the cleanest and nicest. The rest are steps back IMO. In fact, I think this syntax is pretty nice and would be cool if it were implemented, but I don't have high hopes given the previous rejected RFCs and the proximity to stable.

    fn get_mut<lifetime a>(foo: &a mut Foo) -> &a mut Bar { ... }

Also, I personally **don't mind** the 'wordiness' of writing out `lifetime`, but I do think it may be an issue for other people, consider that it would be unique in that most other keywords are shortened (e.g. `fn`, `priv`, `i32`, etc.). If we could come up with a shortened version, it would cut down on the 'wordiness' of it while still being nice and clean, but I can't imagine what shortened version it would be that wouldn't also be nearly as confusing as `'` alone. For example, `lt` would probably too short as to defeat the motivation of this RFC, the alternative shortest I can think of is `life` but that does away with the second and important word, though personally I would be perfectly fine with both. The unmatched `'` alone, like you said, is enough to trip up newcomers; at least `lt` and `life` would be easily searchable and looked up.

**Comment by Ericson2314** [comment]
I would prefer `a: lifetime` or something, for forward compatibility with HKT. Otherwise looks good. Like keeping the `&mut`  together too.

**Comment by nikomatsakis** [comment]
Regardless of the merits of the proposal, I think it comes too late. We can't go changing fundamental parts of the syntax right now.

**Comment by AndyShiue** [comment]
I prefer `~a` than `'a` or `lifetime a` because a single `'` looks strange and and I don't want to type an 8-character keyword, but anyway, it's too late to change ...

**Comment by netvl** [comment]
-1 for all of the reasons already stated in earlier discussions and because it is too late.

**Comment by mahkoh** [comment]
>The ' sigil on lifetimes is, for newcomers to the language, visual noise with little discernible meaning. The unmatched quote is also extremely unnatural for those accustomed to C-style syntax: our main target audience. (Some of the author's more knowledgeable friends, acquainted with functional programming languages and not only C, have expressed the sentiment that they find it weird, and always reflexively want to insert the closing quote.) The rest of Rust's syntax does a fantastic job of fitting new concepts into a familiar C-style syntax in an intuitive wayl; it's only the ' sigil on lifetimes which sticks out like a sore thumb and breaks the metaphor.

>The new syntax with the lifetime keyword is more explicit, meaning it is more verbose and provides greater clarity. Considering that due to excellent lifetime elision, explicit lifetime variables are infrequently required, and that lifetimes are a concept not to be found in any other popular language, this seems like an obviously worthwhile tradeoff.

2015-01-11-160628_689x511_scrot

From http://channel9.msdn.com/Events/Lang-NEXT/Lang-NEXT-2014/Keynote

**Comment by glaebhoerl** [comment]
Yes, it's too late. We should do it anyways. Better late than never.

Rigid adherence to self-imposed deadlines is just a way to avoid having to rationally weigh the costs and benefits.

The question should only be: is the time and effort to make the change worthwhile in light of the future benefits? I think the answer to that question has always been "yes", and if so, then it still is.

**Comment by nagisa** [comment]
I’m perfectly fine with a tick and have come to like it, even. :-1:

**Comment by glaebhoerl** [comment]
It should be gotten rid of not for your sake or mine, but for the legions of C/C++ programmers' who have yet to encounter the language.

(I, personally, can survive the ticks as well.)

**Comment by sinistersnare** [comment]
I think @mahkoh's image is perfect, I have come to like the tick syntax, its simple and understandable. I dont like arguing syntax much, so thats all I want to say :)

**Comment by gulbanana** [comment]
aesthetically, sure, get rid of it. it doesn't seem important enough to spend much effort on but if we happen to live in a perfect world then yes, a keyword seems a bit nicer.

**Comment by marton78** [comment]
+1 For readability and searchability. Better late than sorry!

**Comment by quantheory** [comment]
:-1:

I question the pedagogical benefit of removing the tick. (In fact even as a C++/Python-er I feel the opposite way.)

When starting to learn Rust, I always thought that the `'` was *much more clear* than a long keyword, because it reduces visual clutter while still standing out. It also makes lifetimes and types easier to distinguish when actually used.

It only took a minute to learn what the tick means, and it was hard to forget because it appears everywhere. I just don't think that something used so frequently needs a mnemonic keyword.

**Comment by breckinloggins** [comment]
Is there a higher-level abstraction that, if considered, would make the ```lifetime``` keyword useful semantically as well as syntactically? 

In other words: could ```fn get_mut<my_custom_construct a>(foo: &a mut Foo) -> &a mut Bar { ... }``` ever mean anything cool?

Other possible keywords: ```lives```, ```live```, ```scope``` (cool but wrong, unfortunately), ```life``` (as mentioned)...

+1 on ```&mut{a}``` or even ```&mut<a>``` (if possible). I personally find the ```&mut -> &a mut``` separation odd. Another option is ```&mut(a)```, which is less "pointy".

This is way out there, but could we possibly get rid of the pre-declaration altogether?  In other words, just have ```fn get_mut(foo: &mut(a) Foo) -> &mut(a) Bar {...}``` and simply declare that all lifetime names in the same (module/crate/whatever) with the same name are equal. I don't know the grammar well enough to even know if this is even coherent, but it's an interesting idea.

Finally, I'd like to echo the point that though this would not be a convenient time to change this syntax, if we had a time machine we might visit the future and discover that it was the *only* time we could have done it.

**Comment by glaebhoerl** [comment]
> In other words: could fn get_mut<my_custom_construct a>(foo: &a mut Foo) -> &a mut Bar { ... } ever mean anything cool?

Yes, see my reddit comment about kind ascriptions I linked from the motivation section.

**Comment by Ericson2314** [comment]
On a related note, since `<T: Trait>` isn't deprecated by where clauses, what will kind annotations look like?

**Comment by glaebhoerl** [comment]
http://www.reddit.com/r/programming/comments/2ny8c1/rust_generics_and_collections/cmiqhyx that's my idea

**Comment by Ericson2314** [comment]
Hmm, that works. To play devil's advocate, If you use `'` and `type`, and allow dropping the `type` in the `<type T>` case, `<'a>` falls right out of those rules. Of course `<type<', ', type, '<'>> Q: Foo>` is also the worst syntax ever.

**Comment by nick29581** [comment]
We discussed this at today's triage meeting. The overall feeling was that it is simply too late to make this kind of significant change, especially as there would be lots of discussion and probably a fair bit of design work/ironing out bugs.

**Pull request closed without merging**
