### PR TITLE
RFC to lex binary and octal literals more eagerly.

### PR DESCRIPTION
**Pull request by huonw**
[Rendered](https://github.com/huonw/rfcs/blob/small-bases/text/0000-small-base-lexing.md).

### CODE REVIEW

**Comment by aidancully** [comment]
The part that still strikes me as awkward is that suffixes have an invisible constraint (as in, not obvious at the point where the `suffix` lexeme would be described) that they not begin with the characters `[a-fA-F]`, in order to avoid an ambiguity with hexadecimal numbers. I can't think of a current-rust compatible way to avoid that issue, though. (The best incompatible way of dealing with the issue is, I think, to eliminate suffixes and use type-ascription instead. Which is probably a big lift, but I'd suggest could be mentioned under Alternatives?)

**Comment by huonw** [comment]
While that is a reasonable point (a user-defined suffix must not start with a valid hex char to be usable with hexidecimal literals), I'm not sure it's relevant to this RFC in particular.

That is, even if we had no suffixes, I would still be in favour of this more eager lexing.

**Comment by aidancully** [comment]
If we had no suffixes, the lexing should be even more eager (`0[box][0-9a-zA-Z_]* | [0-9][0-9a-zA-Z_]*`), but that's not an argument against your solution, which I'd support: this seems like an obvious bug in the lexing, to me.

**Comment by Ericson2314** [comment]
What about `([0-9]+ | 0(o|b|x)[0-9a-fA-F]+) suffix` to take your proposal one step further?

**Comment by huonw** [comment]
@Ericson2314 good point! In this case, I think we automatically effectively get that grammar with this change (well, the ability to switch to it backwards compatibly), since e.g. `0b101ABC1234` is lexed as `0b101` with a suffix of `ABC1234`.

**Comment by aidancully** [comment]
There's probably an obvious reason this won't work, but what about requiring `suffix` to begin with `:`? It avoids the ambiguity with potential future suffixes that begin with [a-fA-F], and might be future compatible with using type-ascription to name variables? It'd basically be a limited form of type-ascription, but only for types that have suffixes.

**Comment by Ericson2314** [comment]
@aidancully Interesting! In Haskell type ascription has very low precedence, but this allows a maximally high precedence type ascription to be introduced replacing the lexing suffixes trick backwards compatibly.

**Comment by CloudiDust** [comment]
@aidancully @Ericson2314, +1, this is a neat way to avoid duplicating features once "full" type ascriptions land.

**Comment by steveklabnik** [comment]
Accepted! I'm not going to make a tracking issue, since @huonw already has a patch prepared.

**Pull request merged**
