### PR TITLE
Panicking tasks should abort process if not handled

### PR DESCRIPTION
**Pull request by MichaelGG**
RFC for issue opened here: https://github.com/rust-lang/rust/issues/19610

### CODE REVIEW

**Comment by aturon** [comment]
@MichaelGG I'm catching up on RFC shepherding and wanted to leave some thoughts on this RFC.

### Exception safety

One of the basic issues raised here is dealing with exception safety when data is shared between threads. High-level communication between threads -- locks, semaphores, channels, and so on -- all have built-in support for "handling" a panic from other threads by propagation. While this does not *force* the other threads to panic, it makes clear that a panic has occurred and forces you to opt-in to continuing.

On the other hand, low-level atomics do not provide any such built-in measures. But data manipulated directly via low-level atomics is generally kept in an invariant-maintaining state at all times (i.e., with each atomic update), because other threads can observe the state at all times. That's one of the basic principles behind lock-free data structures. So the exception safety concern is much more limited in such cases.

### What does it mean for a panic on a child thread to be caught?

Connected to the above, to make this idea work in practice we'd need a fuller picture of what it means to "handle" a panic from a child thread. The RFC talks about `try_future` (which is now  basically `Thread::scoped`), but this is by no means the only way to detect and deal with a panic from another thread. As mentioned above, channels, mutexes, and other synchronization constructs also propagate panics.

It seems very unfortunate for a panic to be detected by another thread via a channel, but for the child thread to *still* abort the process. To get around that, all of the above synchronization constructs would have to set some kind of thread-local "panic handled" thread, which itself seems somewhat hokey and error-prone (consider that all future synchronization constructs would need to do this as well).

### Layering on the `abort`

On the other hand, if abort is desired, it's very easy to add via a guard wrapping the body of spawned threads. Once can even create a simple wrapper API around `spawn` to do this. So this is really just a question of defaults. 

To me, asynchronously aborting the process is a somewhat aggressive and opinionated default, and I think it may be reasonable to ask people to opt in to it. (There's precedent for that in some other languages as well.)

### Future-proofing

Above I'm arguing that we shouldn't take this RFC, but what happens if the above arguments turn out to be wrong for some reason or another?

I think in the long run, we may well want to explore something like C++'s `std::terminate`, i.e. a customizable action that's fired whenever an exception is uncaught (though again, "catching" is a bit harder to define in Rust). That would make it even easier for people to choose their desired behavior in a global way, rather than trying to find a one-size-fits-all solution.

**Comment by nikomatsakis** [comment]
I am feeling a bit torn here. On the one hand, I think that the "propagate failure by default" perspective that we have "quasi"-inherited from Erlang is a sensible one. The default behavior probably ought not be to suppress failure (though precedent definitely is all over the map here, from what I can tell).

However, if we made `spawn` abort, then I think the current API as it stands leaves a gap. In particular, we currently have the option to `spawn` asynchronously or synchronously. When the synchronous pattern fits your code, that's great, and it makes the error handling strategy relatively obvious: errors in the child bubble up to the parent, all is hunky dory.

However, there are numerous patterns for which an asynchronous spawn is more appropriate. For example, a CPS-style of execution, where each thread will spawn its successors, or perhaps just send messages that may trigger more work. Now if you are writing code that works in this fashion, and a panic occurs, you may indeed have a plan for how to handle it -- you can e.g. have an RAII guard at the top that catches a panic and sends a message to some central handler. Unfortunately, that doesn't mix well with this RFC, because that panic will still propagate and reuslt in your program being aborted. I think this is partly what @aturon was getting at.

So I feel like this RFC in isolation doesn't feel complete. I'd feel more amenable to this proposal if we altered the API so that there is some way for a thread to indicate that a panic *has* been handled. Some possibilities are a more general `std::terminate`-like mechanism (basically codifying the RAII pattern I described above), a `recover` mechanism, or at least the ability to specify a handler for panic when you launch the thread.

Absent that, the current behavior seems to make sense, because it gives people the ability to build up and choose their error handling strategy of choice (which can easily include an abort).

**Comment by aturon** [comment]
The discussion seems to've stalled out here, but there does seem to be a consensus that there should be *some* way of customizing the behavior of uncaught panics. I'm going to go ahead and close this PR for now (I'm trying to clean up the repo a bit) and open an issue for addressing this in the future.

The main concern in terms of 1.0 commitment is, of course, the default behavior, and I do think we should consider changing that, although abort-by-default is likely to be too strong given the above discussion.

Thanks for the PR!

**Comment by aturon** [comment]
[RFC issue](https://github.com/rust-lang/rfcs/issues/946)

**Comment by MichaelGG** [comment]
Yeah I went over Niko's issue, basically it's not fair to double panic. I've been thinking about it, and I don't think there's a real elegant solution, as Niko points out. Personally I'd just default to panicking and then allow a per-thread handler to decide if it's fatal or not. Even just a global boolean "when-you-die-in-a-thread-you-die-in-real-life" setting would work for me. But a simple hack like that isn't perhaps something we want to commit to at 1.0.

**Pull request closed without merging**
